import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mx-20 mt-24">
        <h1 className="text-4xl font-medium mb-10">Runner&apos;s Workout</h1>
        <Banner />
      </div>
    </div>
  );
}
